name: Feature request
description: Propose an improvement
title: "feat: "
labels: ["type:feature"]
body:
  - type: textarea
    attributes:
      label: Problem
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed solution
    validations:
      required: true
